sudo: required
language: python

notifications:
  slack: $SLACK_CHANNEL

services:
  - docker

#install:
#  - docker build -t elastixtest/test .
#  - docker run -d --name elastix elastixtest/test tail -f /dev/null

script:
  #- docker ps | grep -q elastix
  - ls

#after_failure:
#  - docker logs mycontainer

#after_success:
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then
#    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#    docker push elastixtest/test;
#    fi


